### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by takluyver**
Work towards https://github.com/panosc-eu/WP8/issues/1

I have made the Django code compatible with Python 3.6 (as far as I've managed to test), while retaining compatibility with Python 2.7 for now. I'm doing it like that so that it's possible to merge this even if you're not in a position to move to Python 3 immediately.

Testing: I adapted the `bootstrap-mcweb-standalone.sh` script to create a Docker container based on Ubuntu 18.04 (the commit message for that script indicates that it's meant to be run on Ubuntu 18.04). I set up the Django site inside the container, logged in as djangoadmin (local authentication, not LDAP), ran the default simulation and checked the plots & 'layout' output. Once it was working with Python 2.7, I modified the Docker container to set it up with Python 3.6 (the Python 3 version available in Ubuntu 18.04) and made changes until the same steps worked. I used the same versions of all the dependencies (including Django 1.8.2), only changing the Python version.  I can describe the container setup further if it's of interest - it's in the `docker` branch on my fork of the repo.

Most of the changes were what I'd expect for porting code to Python 3 - the `print()` function, some functions that now return iterators instead of lists, and distinguishing bytes from unicode text.

There was one tricky bit: some of the commands it runs in subprocesses (like `mcplot` and `mcdisplay-webgl`) are shell scripts which invoke `python3` by name to run McStas code. When run from a Python 2 virtualenv, they use the system Python 3 (as intended). When run from a Python 3 virtualenv, they find the Python inside the virtualenv, and then fail because that doesn't have all the necessary dependencies for the McStas code. It's probably best to fix that in McStas by being more explicit about which Python it's using, but for now I've worked around it by putting `/usr/bin` as the first entry on PATH when running those commands, so it correctly finds `/usr/bin/python3`.

### CODE REVIEW

**Comment by takluyver** [comment]
There was some interest in my Docker setup in the meeting on Friday. I don't know much about using it to run the code in production, but I think it's a pretty good solution for running the simulator web-app during development. The main functionality of running the simulation and displaying the results doesn't appear to depend on any persistent state, so it's quite practical to launch it with a blank slate each time, and discard old containers.

I've expanded [my notes on the container setup](https://github.com/takluyver/pan-learning-djangotools/blob/docker/docker-notes.md) with a bit more detail on what I did. To be clear, though, I wrote the container setup as something to use for a few days to test the changes in this PR, and I'm not a container expert, so don't take what I've done too seriously.

**Comment by willend** [comment]
Hi @takluyver,

Sorry for the delay in picking up reviewing this PR, have been really busy, then there was easter etc., but I am now finally on the task.  

Will check out your version of the code, deploy it somewhere, test and get back to you... :)

**Comment by willend** [comment]
@takluyver excellent work setting up the podman solution - very nice for testing indeed! I can confirm this containerisation setup also works nicely with docker here. 

The port to python3 also looks functional and I think the hack to prefix /usr/bin to the PATH when calling the mc* utils is OK for now. 

Perhaps a long-term solution would in fact be to try moving away from the virtualenv all together, i.e. rather enrich the system python3? This at least makes a lot of sense to me if combined with a containerisation-scheme... (Admittedly It has been a while since I looked at / touched this code at all, so I might be missing some obvious gotcha that makes it difficult / impossible to move away from the virtualenv). 

Alternatively we could simply enrich the venv with the needed modules to run mc*, I will be back with a comment later detailing what those dependencies are...

**Comment by willend** [comment]
May I btw. also suggest a follow-up PR to merge the containerisation in?

**Comment by takluyver** [comment]
> Perhaps a long-term solution would in fact be to try moving away from the virtualenv all together, i.e. rather enrich the system python3?

That's probably possible, especially if it's all in a container, but I think it's an advantage to have the web app in a separate Python environment from the simulation code. That way there's no need to worry about whether the dependencies for one of them interfere with the other.

> May I btw. also suggest a follow-up PR to merge the containerisation in?

Certainly, I'll make a PR. This should definitely be seen as a rough starting point for using containers, though.

**Comment by takluyver** [comment]
I've made PR #30 with the containerisation work.

**Pull request merged**
